config/routes.rb
Rails.application.routes.draw do
  root 'works#static' 
  
  devise_for :users
	
  resources :works
  resources :designs

  resources :posts do
    resources :comments
  end

  get 'static', to: 'works#static'
  get 'about', to: 'works#about'
  get 'cases', to: 'designs#cases'
  get 'hw', to: 'designs#hw'
  get 'teacher', to: 'designs#teacher'
  get 'zeit', to: 'designs#zeit'
  get 'mirror', to: 'designs#mirror'
  get 'portfolio', to: 'works#index'
  get 'resume', to: 'works#resume'

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true

  validates_presence_of :body
  validates :name, :email, presence: true, if: -> { user_id.blank? }
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, allow_blank: true

  HUMANIZED_ATTRIBUTES = {
    body: "Comment"
  }
  
  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def title(current_user)
    if current_user && !user
      name_ = "#{name} (#{email})"
    else
      name_ = "#{user.try(:name) || name }"
    end

    "#{name_} posted on #{created_at.strftime("%d %B %Y")}"
  end

end

app/models/message.rb
class Message < ApplicationRecord
	validates :name, :address, :email, :message, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :message, length: {maximum: 500, minimum: 10}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy

  validates_presence_of :name
end

app/models/work.rb
class Work < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :update, :destroy]
  before_action :set_comment, only: [:update, :destroy]
  before_action :authenticate_user!, only: [:update, :destroy]

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user if current_user

    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully posted.'
    else
      render "posts/show"
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: 'Comment was successfully updated.'
    else
      render "posts/show"
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post), notice: 'Comment was successfully deleted.'
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :name, :email)
    end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
    
    
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
		@message = Message.new
	end

	
	def create
    @message = Message.new(message_params)

    if @message.save
      MessageMailer.contact_me(@message).deliver
      flash[:notice] =  "Message received, thanks!"
    else
      flash[:alert] = "There was an error sending your message."
    end
    render :new
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :message, :address)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(id: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :remove_image)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	def index
		@works = Work.all
	end

	def create
		Work.create(work_params)
		redirect_to root_path
	end

	def edit
	end

	private
	def work_params
		params.require(:work).permit(:name, :message, :email, :address)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/designs/index.html.erb
<div class="container">
<div class="row">
		<div id="portfolios" class="col-12">
			<p class="header">UX Designs</p>
			
		</div>
  </div><!--row-->
</div>

  <div class="container">
	<div class="row">
	
		<div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3">
      <div class="hovereffect">

          <%= link_to scroll_reveal(animation: "enter bottom, after 0.3s") do %>
            
              <%= link_to image_tag("SpotifyMockupScreen.jpeg", class: 'img-thumbnail')  %> 
            
            <%= link_to cases_path do %> 
            <div class="overlay">
              <p class="artist-info">
                <em class="port-desc">
                  <span class="artwork-name">Spotify Social Feature</span>
                </em>
                <br />
                <span class="port-desc">Adding A New Feature To An Existing App</span>
                <br />
                <span class="artwork-medium">Research | Information Architecture | Wireframing | Usability Testing | Iteration | </span>
              
              </p><!--artist-info-->
                
             </div><!--overlay-->
             <% end %> 
        
        </div>
            
      <% end %> 
		
			</div><!--col-->
		

		
      <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3">
     
      <div class="hovereffect">
				
				<%= scroll_reveal(animation: "enter bottom, after 0.3s") do %>
          <%= image_tag("new-teacher-image.jpg", class: 'img-thumbnail')  %> 
          <%= link_to teacher_path do %> 
          <div class="overlay">
              <p class="artist-info">
                <em class="port-desc-lite">
                  <span class="artwork-name">Teacher Tussles</span>
                </em>
                <br />
                <span class="port-desc">A mobile application that gamifies stress relief for teachers</span>
                <br />
                <span class="artwork-medium">Research | User Stories | User Flow & Navigation | Wireframing | Usability Testing </span>
                
              </p><!--artist-info-->
                
             </div>
           <% end %> 
          
          </div><!--hovereffect-->
        <% end %> 
		</div>
			
	
		
	</div><!--row-->
</div><!--container-->

<div class="container">
	<div class="row">
		
			<div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3">
       
        <div class="hovereffect">
					
					<%= scroll_reveal(animation: "enter bottom, after 0.3s") do %>
            <%= image_tag("hw.jpg", class: 'img-thumbnail') %> 
            <%= link_to hw_path do %> 
            <div class="overlay">
              <p class="artist-info">
                <em class="port-desc-lite">
                  <span class="artwork-name">HW Tracker</span>
                </em>
                <br />
                <span class="port-desc">A mobile app which allows teachers to provide templated feedback to assignments</span>
                <br />
                <span class="artwork-medium">Research | User Stories | User Flow & Navigation | Wireframing | Usability Testing </span>
                
              </p><!--artist-info-->
                
             </div>
          <% end %> 
        </div><!--hovereffect-->
					<% end %> 
			
	    </div>


  <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3">
     
      <div class="hovereffect">
				
				<%= scroll_reveal(animation: "enter bottom, after 0.3s") do %>
          <%= image_tag("mirror.jpg", class: 'img-thumbnail')  %> 
          <%= link_to mirror_path do %> 
          <div class="overlay">
              <p class="artist-info">
                <em class="port-desc-lite">
                  <span class="artwork-name">Mobile Ecommerce App</span>
                </em>
                <br />
                <span class="port-desc">Design for a mobile application which allows for browsing and online purchasing</span>
                <br />
                <span class="artwork-medium">Competitive Analysis | Primary & Secondary Research | Information Arch | Wireframing | Usability Testing </span>
                
              </p><!--artist-info-->
                
             </div>
          <% end %> 
          </div><!--hovereffect-->
        <% end %> 
		</div>
	
	</div> <!--row--> 
</div> <!--container-->

app/views/designs/show.html.erb
<%= image_tag("HW_Tracker_Case_Study.jpg") %> 
<% end %> 

app/views/designs/zeit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <%= image_tag('ZeitCaseStudy.jpg', class:'img-fluid') %> 
        </div> 
    </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Global site tag (gtags) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-45882604-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date()); 

    gtag('config', 'UA-45882604-1'); 
  </script>
  
    <title>PersonalPortfolioSite</title>
    <%= csrf_meta_tags %>
    
    <link rel="shortcut icon" href="http://surveygizmolibrary.s3.amazonaws.com/library/650781/square_logo.ico" type="image/x-icon">
    
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
    
    
    <script src="https://use.fontawesome.com/4d2ab3f1e4.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  
  <div id="flex-content-container">
  
  	<nav class="navbar sticky-top navbar-toggleable-md navbar-inverse">


      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
        <%= link_to image_tag("square_logo.png", id: 'nav-pic'), root_path  %> 
        
      

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
            <a class="nav-link" <%= link_to 'About', about_path %><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" <%= link_to 'Contact', new_message_path %><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" <%= link_to 'Resume', resume_path %><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" <%= link_to 'Blog', posts_path %><span class="sr-only">(current)</span></a>
          </li>
          
        </ul>
        
        <% if current_user %>
          <span class="btn"><%= link_to('Logout', destroy_user_session_path, method: :delete, class: "text-white") %>
        <% end %>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>

  </div><!--flex-content--> 

   <div id="footer">
    	<div class="container">
    		<div class="row">
	    		<div class="col-12 col-sm-6">
	    			<b>Contact Info</b>
	    			<br />
	    			youngerik26@gmail.com
	    			<br />
	    			3628 Shaffer Rd
	    			<br />
	    			Rock Creek, Ohio, 44084
	    		</div><!-- div class col-12 -->
	    		<div class="col-12 col-sm-6 social">
	    			<b>Social</b>
	    			<br />
	    			<br />
	    				<%= link_to 'https://github.com/erikyoung' do %>
	    				<span class="fab fa-github-square fa-2x social-button"></span>
	    				<% end %>
	    				<%= link_to 'https://www.facebook.com/erik.young.923' do %>
  						<span class="fab fa-facebook-square fa-2x social-button"></span>
  						<% end %>
  						<%= link_to 'https://twitter.com/youngerik26' do %>
  						<span class="fab fa-twitter-square fa-2x social-button"></span>
  						<% end %> 
  						<%= link_to 'https://medium.com/@erikyoung_58444' do %> 
  						<span class="fab fa-medium fa-2x social-button"></span>
  						<% end %> 
	    		</div><!-- col-12 -->
    		</div><!-- row -->
   		</div> <!-- div container -->
   </div><!-- footer -->

  </body>
</html>

app/views/messages/new.html.erb
<div class="container">
  <div class="row">
  <div class="col-10 offset-1 mt-5 align-items-center">
    
      <h1 class="text-center">Let's Keep in Contact</h1>
      <%= simple_form_for @message, url: create_message_url, defaults: { input_html: { class: 'default_class' } } do |f| %>
        <%= f.input :name, input_html: { class: 'my_class' }, label_html: { class: 'labels' }  %> 
        
        <small class="form-text text-muted">What your friends call you</small>
        <%= f.input :address, label_html: { class: 'labels' } %> 
        <small class="form-text text-muted">Somewhere you go a lot</small>
        <%= f.input :email, label_html: { class: 'labels' }, placeholder: 'user@domain.com' %>
        <%= f.input :message, label_html: { class: 'labels' },  placeholder: "I'm contacting you about..." %> 
        <small class="form-text text-muted">Hopefully, about a project</small>
        <br />
     
      <%= f.submit 'Contact Me', class: 'btn btn-primary btn-lg btn-block' %>
    <% end %>
    </div> 
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1 mt-5 align-items-center">

      <h1>Editing Post</h1>

      <%= render 'form', post: @post %>
    </div> 
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1 mt-5 align-items-center">
      <% if current_user %>
        <div class="row float-right">
          
        <div class="btn btn-warning"><%= link_to 'New Post', new_post_path, class: "text-white" %></div>
        </div>
      <% end %>
      <% @posts.each_with_index do |post, i| %>
        <div class="<%= 'mt-5' if i != 0 %> clearfix">
          <div class="">
            <div class="post-title font-weight-bold text-center w-100">
              <h2><%= link_to post.title, post %> <%=  %></h2>
            </div>
            <div class="post-image text-center w-100 mt-5"><%= image_tag post.image, class: "" %></div>
            <div class="post-body text-justify mt-4"><%= post.body.html_safe %></div>
          </div>
          <% if current_user %>
            <div class="float-right mt-2">
              <span class="position-relative ml-2"><%= link_to 'Edit', edit_post_path(post) %></span>
              <span class="position-relative ml-2"><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
            </div>
          <% end %>
        </div>
        <br><br>
      <% end %>
    </div> 
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1 mt-5 align-items-center">

      <h1>New Post</h1>

      <%= render 'form', post: @post %>
    </div> 
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1 mt-5 align-items-center">
      <div class="clearfix">
        <div class="">
          <div class="post-title font-weight-bold text-center w-100"><h2><%= @post.title %></h2></div>
          <div class="post-image text-center w-100 mt-5"><%= image_tag @post.image, class: "" %></div>
          <div class="post-body text-justify mt-4"><%= @post.body.html_safe %></div>
        </div>
        <% if current_user %>
          <div class="clearfix">
            <div class="float-right mt-2">
              <span class="position-relative ml-2"><%= link_to 'Edit', edit_post_path(@post) %></span>
              <span class="position-relative ml-2"><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
            </div>
          </div>
        <% end %>

        <div class="mt-5">
          <p><strong>Comments</strong></p>
          <hr>
          <% @post.comments.order(id: :asc).each do |comment| %>
            <div class="mt-4">
            <p class="comment-title"><small><%= comment.title(current_user) %></small></p>
            <div class="comment-body"><%= comment.body %></div>
            <% if current_user %>
              <div class="clearfix">
                <div class="float-right">
                  <span class="position-relative"><%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %></span>
                </div>
              </div>
            <% end %>
            </div>
          <% end %>
        </div>

        <div class="mt-5">
          <% if current_user %>
            <%= simple_form_for @comment, url: post_comments_path(@post), html: {class: "mt-3"} do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

              <div class="form-inputs">
                <%= f.input :body, as: :text, :input_html => { :class => 'w-75', placeholder: "New Comment", rows: 5}, label: false  %>
                <div class="form-actions">
                  <%= f.button :submit, "Post", class: "btn btn-primary" %>
                </div>
              </div>
            <% end %>
          <% else %>
            <%= simple_form_for @comment, url: post_comments_path(@post), html: {class: "mt-3"} do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

              <div class="form-inputs">
                <%= f.input :name, :input_html => { :class => 'w-50', placeholder: "Name" }, label: false %>
                <%= f.input :email, :input_html => { :class => 'w-50', placeholder: "Email" }, label: false  %>
                <%= f.input :body, as: :text, :input_html => { :class => 'w-75', placeholder: "New Comment", rows: 5}, label: false  %>
                <div class="form-actions">
                  <%= f.button :submit, "Post", class: "btn btn-primary" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

      </div>
      <br><br>
    </div> 
  </div>
</div>

app/views/works/static.html.erb
<div class="main-carousel">
	<div class="container">
		<div class="row">
		
				<div class="col-6 col-sm-6 col-md-6 col-lg-6 mx-auto px-2 intro-message">
				
					<span id="erik-font">I'm Erik</span>
					<h1 class="info-me">Designer&nbsp;&amp; Front-end Developer. Based&nbsp;in Columbus, Ohio.</h1>
					
					
					<hr class="intro-divider">
					<ul class="list-inline intro-social-buttons">
						<li>
							<%= link_to 'https://github.com/erikyoung' do %>
	    				<span class="fab fa-github-square fa-2x social-button"></span>
	    				<% end %>
						</li>
						<li>
							<%= link_to 'https://www.linkedin.com/in/erik-young-b2727161/' do %>
	    				<span class="fab fa-linkedin fa-2x social-button"></span>
	    				<% end %> 
						</li>
					</ul>

					<a href="#" class="scroll-to"></a>
				</div>
				
			</div>
			
		</div>	
		
</div>
<div class="featured-artwork-box container-fluid">
	<div class="row">
		<div id="portfolios" class="col-12">
			<p class="header">UX Designs</p>
			
		</div>
	</div><!--row-->


	<div class="container" style="display:flex;">
	<div class="row pt-5 m-auto">
	
		<div class="col col-sm-12 col-md-12 col-lg-6 col-xl-6 pt-3 mt-3 pb-3" id="design-main-page">
		
			<div class="card border-white">
				<div class="card-body">
					<%= link_to mirror_path do %> 
			
					<%= scroll_reveal(animation: "enter bottom over 2s after 0.3s" ) do %>
					<div class="img-div">
						<%= image_tag("mirror-latest.png", class: 'img-thumbnail', id:'img1')  %> 
					</div>
					
						<% end %> 
				</div><!--card-body-->
				<% end %> 
			</div><!--card-->
			
			
		</div><!--col-->

	<div class="col col-sm-12 col-md-12 col-lg-6 col-xl-6 pt-3 mt-3 pb-3" id="design-main-page">
		
		<div class="card border-white">
			<div class="card-body">
				<%= link_to hw_path do %> 
				<%= scroll_reveal(animation: "enter bottom over 2s after 0.3s") do %>
					<%= image_tag("backgroundNeeded.png", class: 'img-thumbnail', id:'img2')  %> 
					<% end %> 
			</div><!--card-body--> 
			<% end %> 
		</div><!--card-->
				
	</div><!--col-->
		
		
	</div><!--row-->
</div><!--container-->

<div class="container">
	<div class="row pt-5 m-auto">
	
		<div class="col col-sm-12 col-md-12 col-lg-6 col-xl-6 pt-3 mt-3 pb-3" id="design-main-page">
		
			<div class="card border-white">
				<div class="card-body">
					<%= link_to teacher_path do %> 
			
					<%= scroll_reveal(animation: "enter bottom over 2s after 0.3s" ) do %>
					<div class="img-div">
						<%= image_tag("teachertussle-Recovered.png", class: 'img-thumbnail', id:'img1')  %> 
					</div>
					
						<% end %> 
				</div><!--card-body-->
				<% end %> 
			</div><!--card-->

			</div><!--col-->

		<div class="col col-sm-12 col-md-12 col-lg-6 col-xl-6 pt-3 mt-3 pb-3" id="design-main-page">
		
		<div class="card border-white">
			<div class="card-body">
				<%= link_to cases_path do %> 
				<%= scroll_reveal(animation: "enter bottom over 2s after 0.3s") do %>
					<%= image_tag("spotify-latest-Recovered.png", class: 'img-thumbnail', id:'img2')  %> 
					<% end %> 
			</div><!--card-body--> 
			<% end %> 
		</div><!--card-->
				
	</div><!--col-->

	</div> <!--row--> 
	</div><!--container--> 



 

<div id="portfolios" class="col-12">
	<p class="header">Web Development Projects</p>
</div>



<div class="container" style="display:flex;flex-direction:row;">



	<div class="row pt-3 pb-5 m-auto">
	
		<div class="col col-sm-12 col-md-12 col-lg-4 col-xl-4 pt-3 mt-1 pb-3" id="design-main-page">

			<div class="card card-custom bg-white border-white border-0">
				<div class="card-custom-img">
					<a href="https://restaurant-erik.herokuapp.com/" target="_blank">
						<%= scroll_reveal(animation: "enter bottom over 2s after 0.3s") do %>
							<%= image_tag("restaurant.png", class: 'img-thumbnail') %> 
						</a>
						<% end %>
				</div><!--card-custom-img-->

					
				
			</div> <!--card-->
		</div><!--col-->



		<div class="col col-sm-12 col-md-12 col-lg-4 col-xl-4 pt-3 mt-1 pb-3" id="design-main-page">

			<div class="card card-custom bg-white border-white border-0">
				<div class="card-custom-img">
					<a href="https://nomster.herokuapp.com/" target="_blank">
					<%= scroll_reveal(animation: "enter bottom over 2s after 0.3s") do %>
						<%= image_tag("NomsterRVSD", class: 'img-thumbnail')  %> 
					</a>
					<% end %> 
				</div><!--card-custom-img-->
				
				</div><!--card-->
		</div><!--col-->
		
			
			<div class="col col-sm-12 col-md-12 col-lg-4 col-xl-4 pt-3 mt-1 pb-3" id="design-main-page">
				<div class="card card-custom bg-white border-white border-0">
					<div class="card-custom-img">
							<a href="https://inspiring-blackwell-24e345.netlify.com/" target="_blank">
							<%= scroll_reveal(animation: "enter bottom over 2s after 0.3s") do %>
								<%= image_tag("SoundCloud.png", class: 'img-thumbnail') %> 
							</a>
							<% end %> 
					</div><!--custom-img-->
						
				</div><!--card-->	
			</div><!--col-->


		
			
			
			</div><!-- card -->
		</div><!--col-->
		
	</div><!--row-->
</div><!--container--> 




 




			</div><!-- featured-art -->
		</div><!--featured-artwork-top -->
	</div><!--portfolios -->
</div><!--featured-artwork -->